"use client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { ReactQueryClientProvider } from "./components/reactQueryClientProvider";
import NavLinks from "./components/home/NavLinks";
import { Provider } from "react-redux";
import "./global.css";
import { store } from "./lib/store";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = DM_Sans({ subsets: ["latin"] });
const metadata: Metadata = {
  title: "start up",
  description: "Generated by create next app",
};
const queryClient = new QueryClient({
  defaultOptions: {
    queries: { refetchOnWindowFocus: false, retry: false, staleTime: Infinity },
  },
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="">
      <QueryClientProvider client={queryClient}>
      <ReactQueryClientProvider>
        <Provider store={store}>
          <body className={inter.className}>
            <NavLinks />
            {children}
          </body>
        </Provider>
      </ReactQueryClientProvider>
      </QueryClientProvider>
    </html>
  );
}
